"""Add advanced search filter fields

Revision ID: 9082cc955b23
Revises: 57b388d875c7
Create Date: 2026-01-07 18:17:23.504760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9082cc955b23'
down_revision = '57b388d875c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('barrio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subtipo_propiedad', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tipo_alquiler', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_propiedad', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('metros_cuadrados', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_column('metros_cuadrados')
        batch_op.drop_column('estado_propiedad')
        batch_op.drop_column('tipo_alquiler')
        batch_op.drop_column('subtipo_propiedad')
        batch_op.drop_column('barrio')
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###
