"""Add username column to usuarios table

Revision ID: 95733a3ff5a2
Revises: b0d271e96d57
Create Date: 2026-05-29 02:48:37.622665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95733a3ff5a2'
down_revision = 'b0d271e96d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
