"""add fecha_baja_programada and update estado workflow

Revision ID: a1b2c3d4e5f6
Revises: 9082cc955b23
Create Date: 2026-01-11 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '9082cc955b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_baja_programada', sa.Date(), nullable=True))
    
    # Update existing estado values to new workflow
    # 'activo' -> 'activada', 'inactivo' -> 'desactivada'
    op.execute("UPDATE ofertas SET estado = 'activada' WHERE estado = 'activo'")
    op.execute("UPDATE ofertas SET estado = 'desactivada' WHERE estado = 'inactivo'")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert estado values
    op.execute("UPDATE ofertas SET estado = 'activo' WHERE estado = 'activada'")
    op.execute("UPDATE ofertas SET estado = 'inactivo' WHERE estado = 'desactivada'")
    op.execute("UPDATE ofertas SET estado = 'activo' WHERE estado = 'abierta'")
    op.execute("UPDATE ofertas SET estado = 'inactivo' WHERE estado = 'caducada'")
    
    with op.batch_alter_table('ofertas', schema=None) as batch_op:
        batch_op.drop_column('fecha_baja_programada')
    
    # ### end Alembic commands ###
