"""Add Reserva model and Usuario fields

Revision ID: b0d271e96d57
Revises: a1b2c3d4e5f6
Create Date: 2026-05-28 19:28:56.498441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0d271e96d57'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sobre_mi', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('sobre_mi')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
